# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "zh-CNS"
title: Likecat
subtitle: Bojun Zhang
email: a@likecat.cn
description: >- # this means to ignore newlines until "baseurl:"
  This is a personal website under design, and I haven't decided what interesting things should be put on it.
baseurl: ""
url: "https://likecat.cn"
teaser: /assets/images/teaser.jpg
repository: "zbj178016760/likecat.cn"
# twitter_username: username
github_username: zbj178016760

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
breadcrumbs: true
search: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

atom_feed:
  hide: true

author:
  name: "Bojun Zhang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "PhD candidate in Mechanical Engineering, but enjoy programming."
  location: "Beijing, China"
  links:
    - label: "Likecat.cn"
      icon: "fas fa-fw fa-home"
      url: "https://likecat.cn"
    - label: "a@likecat.cn"
      icon: "fas fa-fw fa-envelope"
      url: "mailto://a@likecat.cn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zbj178016760"
    - label: "Orcid"
      icon: "fas fa-fw fa-user-graduate"
      url: "https://orcid.org/0000-0002-1867-0243"

footer:
  links:
    - label: "Likecat.cn"
      icon: "fas fa-fw fa-home"
      url: "https://likecat.cn"
    - label: "a@likecat.cn"
      icon: "fas fa-fw fa-envelope"
      url: "mailto://a@likecat.cn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zbj178016760"
    - label: "Orcid"
      icon: "fas fa-fw fa-user-graduate"
      url: "https://orcid.org/0000-0002-1867-0243"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
